# a=input()
# b=input()
# c=input()
# d=input()
# e=input()
# set=(a,b,c,d,e)
# print(set)

name1,name2,name3,name4,name5=input(": "),input(": "),input(": "),input(": "),input(": ")
f=(name1,name2,name3,name4,name5)
print(f)